Cachkozavr_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from posts.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('search/', views.post_search_view, name='post_search'),
    path('<slug:post>/', views.post_detail, name='post_detail'),

    # Изменяем регулярное выражение для tag_slug, чтобы поддерживать кириллицу
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),

]

posts/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, AbstractUser


from taggit.managers import TaggableManager
from .utils import time_since_published, get_short_body
from django.urls import reverse
from .utils import custom_slugify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset() \
            .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique_for_date='published_date')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')

    body = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    video = models.FileField(upload_to='videos/', blank=True, null=True)

    published_date = models.DateTimeField(default=timezone.now)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)

    status = models.CharField(choices=Status.choices, default=Status.DRAFT, max_length=20)

    tags = TaggableManager()

    votes_up_count = models.PositiveIntegerField(default=0)
    votes_down_count = models.PositiveIntegerField(default=0)
    rating = models.IntegerField(default=0)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-created_date']
        indexes = [models.Index(fields=['-published_date'])]

    def __str__(self):
        return self.title

    def time_since_published(self):
        return time_since_published(self.published_date)

    def get_short_body(self, length=800):
        return get_short_body(self.body, length)

    def get_absolute_url(self):
        return reverse('posts:post_detail',
                       args=[self.slug])

    def save(self, *args, **kwargs):
        # Если пост новый и слаг не установлен, создаём слаг
        if not self.slug:
            self.slug = custom_slugify(self.title)
        # Сохраняем пост с тегами
        super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=200)
    body = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created_date']
        indexes = [models.Index(fields=['-created_date'])]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

    def time_since_published(self):
        return time_since_published(self.created_date)


class CustomUser(AbstractUser):
    date_of_birth = models.DateField(blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    rating = models.IntegerField(default=0)
    votes_up_count = models.PositiveIntegerField(default=0)
    votes_down_count = models.PositiveIntegerField(default=0)
    comments_count = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.username

posts/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']
        labels = {
            'name':'',
            'body': '',  # Убираем метку для поля body
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control comment-name-input',
                                           'placeholder': 'Ваше имя'}),
            'body': forms.Textarea(attrs={'class': 'form-control comment-body-input',
                                          'placeholder': 'Напишите, что вы думаете...'}),
        }


class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control search-input',}))

posts/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.db.models import Count, Q
from django.http import JsonResponse
from django.contrib import messages
from django.urls import reverse

from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

from taggit.models import Tag
from .models import Post
from .forms import CommentForm, SearchForm


def post_list(request, tag_slug=None):
    posts = Post.published.annotate(total_comments=Count(
        'comments',
        filter=Q(comments__active=True)))

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag,
                                slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    return render(request,
                  'posts/post/list.html',
                  {'posts': posts, 'tag': tag})


def post_detail(request, post):
    post = get_object_or_404(Post,
                             slug=post,
                             status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True).order_by('-created_date')
    form = CommentForm()

    return render(request,
                  'posts/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({'success': True, 'comment': {
                'id': comment.id,
                'name': comment.name,
                'body': comment.body,
                'created_date': comment.created_date.strftime("%d.%m.%Y в %H:%M")
            }})
        else:
            messages.success(request, 'Комментарий успешно добавлен.')
            return redirect(reverse('posts:post_detail', kwargs={'post': post.slug}))
    else:
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({'success': False, 'errors': form.errors})
        else:
            messages.error(request, 'Ошибка при добавлении комментария. Пожалуйста, проверьте введенные данные.')
            return redirect(reverse('posts:post_detail', kwargs={'post': post.slug}))


def post_search_view(request):
    query = request.GET.get('query', '')
    if query:
        search_query = SearchQuery(query, config='simple')
        posts = Post.published.annotate(
            search=SearchVector('title', 'body', config='simple'),
            rank=SearchRank(SearchVector('title', 'body', config='simple'), search_query)
        ).filter(
            Q(search=search_query)
        ).order_by('-rank')
    else:
        posts = Post.published.none()
    context = {
        'posts': posts,
        'query': query,
    }
    return render(request, 'posts/post/search_results.html', context)

posts/templates/posts/post/detail.html
{% extends 'posts/base.html' %}
{% load static %}

<head>
    <script src="https://cdn.jsdelivr.net/npm/date-fns@2.22.1/dist/date-fns.min.js"></script>
    {% block css %}
        <link rel="stylesheet" href="{% static "css/post-detail.css" %}">
        <link rel="stylesheet" href="{% static "css/main.css" %}">
    {% endblock %}
    <title> {% block title %}{{ post.title }}{% endblock %}</title>
</head>

<body>
<div class="container">
    <main>
        {% if tag %}
            <h2>Posts tagged with "{{ tag.name }}"</h2>
        {% endif %}
        {% block content %}
            <div class="post">
                <div class="vote">
                    <div class="vote-section">
                        <svg viewBox="0 0 24 24">
                            <path d="M7 14l5-5 5 5z"></path>
                        </svg>
                        <span class="vote-count">{{ post.rating }}</span>
                        <svg viewBox="0 0 24 24">
                            <path d="M7 10l5 5 5-5z"></path>
                        </svg>
                    </div>
                    <div class="hide-button">
                        <button class="toggle-content">-</button>
                    </div>

                </div>
                <div class="post-content">
                    <div class="post-title">
                        {{ post.title }}
                    </div>
                    <div class="post-meta">
                        <a href="#">{{ post.author }}</a> • {{ post.time_since_published }}
                    </div>
                    <div class="post-tags">
                        {% for tag in post.tags.all %}
                            <a href="{% url "posts:post_list_by_tag" tag.slug %}">
                                <p class="tag">{{ tag.name }}</p>
                            </a>

                        {% endfor %}
                    </div>
                    <div class="post-text">
                        <p>{{ post.body }}</p>
                    </div>
                    <div class="post-actions">
                        <div class="comments">
                            <svg viewBox="0 0 24 24">
                                <path d="M21.99 4c0-1.1-.89-2-1.99-2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h14l4 4-.01-18z">
                                </path>
                            </svg>
                            {% with comments.count as total_comments %}
                                <span>{{ total_comments }}</span>
                            {% endwith %}
                        </div>
                        <div class="views">
                            <svg viewBox="0 0 24 24">
                                <path
                                        d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 17c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3z">
                                </path>
                            </svg>
                            <span>7376</span>
                        </div>
                        <div class="save">
                            <svg viewBox="0 0 24 24">
                                <path d="M17 3H7c-1.1 0-1.99.9-1.99 2L5 21l7-3 7 3V5c0-1.1-.9-2-2-2z"></path>
                            </svg>
                        </div>
                        <div class="share">
                            <svg viewBox="0 0 24 24">
                                <path
                                        d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92 1.61 0 2.92-1.31 2.92-2.92s-1.31-2.92-2.92-2.92z">
                                </path>
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
            <div class="comments-section" id="comments">
                <h2>Комментарии</h2>
                <div class="dividing-section"></div>
                {% include "posts/post/includes/comment_form.html" %}
                <div id="comments-container">
                    {% for comment in post.comments.all %}
                        <div class="comment" id="comment-{{ comment.id }}">
                            <div class="comment-content">
                                <div class="comment-meta">
                                    Опубликовано <a href="#">{{ comment.name }}</a> • {{ comment.time_since_published }}
                                    • ({{ comment.created_date|date:"d.m.Y в H:i" }})
                                </div>
                                <div class="comment-text">
                                    <p>{{ comment.body|linebreaks }}</p>
                                </div>
                                <button class="reply-button" data-comment-id="{{ comment.id }}"
                                        data-author="{{ comment.name }}">Ответить
                                </button>
                                <div class="dividing-section"></div>
                            </div>
                        </div>

                    {% endfor %}
                </div>
                <div class="dividing-section"></div>
            </div>
        {% endblock %}
    </main>
</div>
{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/2.0.3/marked.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'scripts/add_comment.js' %}"></script>
{% endblock %}
</body>

posts/templates/posts/post/list.html
{% extends 'posts/base.html' %}
{% load static %}

<head>
    <script src="https://cdn.jsdelivr.net/npm/date-fns@2.22.1/dist/date-fns.min.js"></script>
    {% block css %}
        <link rel="stylesheet" href="{% static "css/main.css" %}">
    {% endblock %}
    <title> {% block title %}Горячее{% endblock %}</title>
</head>

<body>
<div class="container">
    <main>

        {% if tag %}
            <h2>Posts tagged with "{{ tag.name }}"</h2>
        {% endif %}
        {% block content %}
            {% for post in posts %}
                <div class="post">
                    <div class="vote">
                        <div class="vote-section">
                            <button class="vote-btn">
                                <svg viewBox="0 0 24 24">
                                    <path d="M7 14l5-5 5 5z"></path>
                                </svg>
                            </button>
                            <span class="vote-count" id="rating-{{ post.id }}">{{ post.rating }}</span>
                            <button class="vote-btn">
                                <svg viewBox="0 0 24 24">
                                    <path d="M7 10l5 5 5-5z"></path>
                                </svg>
                            </button>

                        </div>
                        <div class="hide-button">
                            <button class="toggle-content">-</button>
                        </div>
                    </div>
                    <div class="post-content">
                        <div class="post-title">
                            <a href="{{ post.get_absolute_url }}" class="post-link">
                                {{ post.title }}
                            </a>
                        </div>
                        <div class="post-meta">
                            <a href="#">{{ post.author }}</a> • {{ post.time_since_published }}
                        </div>
                        <div class="post-tags">
                            {% for tag in post.tags.all %}
                                <a href="{% url "posts:post_list_by_tag" tag.slug %}">
                                    <p class="tag">{{ tag.name }}</p>
                                </a>
                            {% endfor %}
                        </div>
                        <div class="post-text" data-full-content="{{ post.body }}"
                             data-short-length="{{ post.get_short_body | length }}">
                            <p>{{ post.get_short_body }}</p>
                        </div>
                        <div class="post-actions">
                            <a href="{{ post.get_absolute_url }}#comments" class="comments-link" target="_blank">
                                <div class="comments">
                                    <svg viewBox="0 0 24 24">
                                        <path d="M21.99 4c0-1.1-.89-2-1.99-2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h14l4 4-.01-18z"></path>
                                    </svg>
                                    <span>{{ post.comments.all|length }}</span>
                                </div>
                            </a>
                            <div class="views">
                                <svg viewBox="0 0 24 24">
                                    <path d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 17c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3z"></path>
                                </svg>
                                <span>7376</span>
                            </div>
                            <div class="save">
                                <svg viewBox="0 0 24 24">
                                    <path d="M17 3H7c-1.1 0-1.99.9-1.99 2L5 21l7-3 7 3V5c0-1.1-.9-2-2-2z"></path>
                                </svg>
                            </div>
                            <div class="share">
                                <svg viewBox="0 0 24 24">
                                    <path d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92 1.61 0 2.92-1.31 2.92-2.92s-1.31-2.92-2.92-2.92z"></path>
                                </svg>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endblock %}
    </main>
</div>


{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'scripts/left-toggle-content-button.js' %}"></script>
    <script src="{% static 'scripts/post_text_expand.js' %}"></script>


{% endblock %}
</body>