Cachkozavr_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from posts.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('search/', views.post_search_view, name='post_search'),
    path('<slug:post>/', views.post_detail, name='post_detail'),

    # Изменяем регулярное выражение для tag_slug, чтобы поддерживать кириллицу
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),

]

posts/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, AbstractUser


from taggit.managers import TaggableManager
from .utils import time_since_published, get_short_body
from django.urls import reverse
from .utils import custom_slugify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset() \
            .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique_for_date='published_date')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')

    body = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    video = models.FileField(upload_to='videos/', blank=True, null=True)

    published_date = models.DateTimeField(default=timezone.now)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)

    status = models.CharField(choices=Status.choices, default=Status.DRAFT, max_length=20)

    tags = TaggableManager()

    votes_up_count = models.PositiveIntegerField(default=0)
    votes_down_count = models.PositiveIntegerField(default=0)
    rating = models.IntegerField(default=0)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-created_date']
        indexes = [models.Index(fields=['-published_date'])]

    def __str__(self):
        return self.title

    def time_since_published(self):
        return time_since_published(self.published_date)

    def get_short_body(self, length=800):
        return get_short_body(self.body, length)

    def get_absolute_url(self):
        return reverse('posts:post_detail',
                       args=[self.slug])

    def save(self, *args, **kwargs):
        # Если пост новый и слаг не установлен, создаём слаг
        if not self.slug:
            self.slug = custom_slugify(self.title)
        # Сохраняем пост с тегами
        super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=200)
    body = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created_date']
        indexes = [models.Index(fields=['-created_date'])]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

    def time_since_published(self):
        return time_since_published(self.created_date)


class CustomUser(AbstractUser):
    date_of_birth = models.DateField(blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    rating = models.IntegerField(default=0)
    votes_up_count = models.PositiveIntegerField(default=0)
    votes_down_count = models.PositiveIntegerField(default=0)
    comments_count = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.username

posts/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']
        labels = {
            'name':'',
            'body': '',  # Убираем метку для поля body
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control comment-name-input',
                                           'placeholder': 'Ваше имя'}),
            'body': forms.Textarea(attrs={'class': 'form-control comment-body-input',
                                          'placeholder': 'Напишите, что вы думаете...'}),
        }


class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control search-input',}))

posts/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.db.models import Count, Q
from django.http import JsonResponse
from django.contrib import messages
from django.urls import reverse

from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

from taggit.models import Tag
from .models import Post
from .forms import CommentForm, SearchForm


def post_list(request, tag_slug=None):
    posts = Post.published.annotate(total_comments=Count(
        'comments',
        filter=Q(comments__active=True)))

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag,
                                slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    return render(request,
                  'posts/post/list.html',
                  {'posts': posts, 'tag': tag})


def post_detail(request, post):
    post = get_object_or_404(Post,
                             slug=post,
                             status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True).order_by('-created_date')
    form = CommentForm()

    return render(request,
                  'posts/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({'success': True, 'comment': {
                'id': comment.id,
                'name': comment.name,
                'body': comment.body,
                'created_date': comment.created_date.strftime("%d.%m.%Y в %H:%M")
            }})
        else:
            messages.success(request, 'Комментарий успешно добавлен.')
            return redirect(reverse('posts:post_detail', kwargs={'post': post.slug}))
    else:
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({'success': False, 'errors': form.errors})
        else:
            messages.error(request, 'Ошибка при добавлении комментария. Пожалуйста, проверьте введенные данные.')
            return redirect(reverse('posts:post_detail', kwargs={'post': post.slug}))


def post_search_view(request):
    query = request.GET.get('query', '')
    if query:
        search_query = SearchQuery(query, config='simple')
        posts = Post.published.annotate(
            search=SearchVector('title', 'body', config='simple'),
            rank=SearchRank(SearchVector('title', 'body', config='simple'), search_query)
        ).filter(
            Q(search=search_query)
        ).order_by('-rank')
    else:
        posts = Post.published.none()
    context = {
        'posts': posts,
        'query': query,
    }
    return render(request, 'posts/post/search_results.html', context)

posts/templates/posts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static "images/favicon.png" %}" type="image/png">

    {% block css %}{% endblock %}

    <title> {% block title %}{% endblock %}</title>
</head>

<body>
<div class="container">
    <nav>
        <a href="{% url 'posts:post_list' %}">
            <div class="logo">
                <img src="{% static 'images/logo.png' %}" alt="Logo" width="50" height="50">
                <p>Kachkozavr</p>
            </div>
        </a>
        <div class="nav-center">
            <a href="/hot">Горячее</a>
            <a href="/best">Лучшее</a>
            <a href="/fresh">Свежее</a>
        </div>
        <div class="nav-right">
            <div class="search-container">
                <form method="get" action="{% url 'posts:post_search' %}">
                    <svg class="search-icon" viewBox="0 0 24 24" style="cursor: pointer;">
                        <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/>
                    </svg>
                    <input type="text" name="query" class="search-input" placeholder="Поиск..."
                           value="{{ request.GET.query|default_if_none:'' }}">
                </form>
            </div>
            <svg viewBox="0 0 24 24">
                <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/>
            </svg>
            <svg viewBox="0 0 24 24">
                <path
                        d="M12 22c1.1 0 2-.9 2-2h-4c0 1.1.89 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"/>
            </svg>
            <div class="avatar"></div>
        </div>

    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <div class="sidebar-top">
        SideBar-TOP
        <div class="sidebar-top-content">
            sdfsdfdf2222222222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        </div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf22222</div>
        <div class="sidebar-top-content">
            sdfsdfdf2222222222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        </div>
    </div>
    <div class="sidebar-bottom">
        SideBar-BOTTOM
        <div class="sidebar-top-content">
            sdfsdfdf2222222222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        </div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf</div>
        <div>sdfsdfdf22222</div>
        <div class="sidebar-top-content">
            sdfsdfdf2222222222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        </div>
    </div>

</div>

<script src="{% static 'scripts/search-toggle.js' %}"></script>
{% block scripts %}

{% endblock %}
</body>

</html>